# Nixpacks configuration for Astro Static Site
[providers]
nodejs = "20"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

# Specify the static directory
[staticDirs]
"/" = "dist"