# Nixpacks configuration for Prowl (Astro Static Site)

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npm install -g http-server"]

[start]
cmd = "http-server dist -p ${PORT:-80} -a 0.0.0.0 --no-dotfiles -c-1"