# Nixpacks configuration for Prowl (Astro Static Site)

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npx serve dist -l 0.0.0.0:${PORT:-80} --no-request-logging --no-clipboard"