# Nixpacks configuration for Prowl (Astro Static Site)
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[staticDirs]
"/" = "dist"

[start]
# For static sites, Nixpacks automatically uses nginx
# This is only used if static mode is not enabled
cmd = "npx serve dist -l ${PORT:-3000}"