# Nixpacks configuration for Prowl
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx astro preview --host 0.0.0.0 --port ${PORT:-4321}"