// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSessionGoal = `-- name: DeleteSessionGoal :exec
DELETE FROM session_goals WHERE session_id = ?
`

func (q *Queries) DeleteSessionGoal(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionGoalStmt, deleteSessionGoal, sessionID)
	return err
}

const getSessionGoal = `-- name: GetSessionGoal :one
SELECT session_id, id, objective, status, token_budget, tokens_used, time_used_seconds, created_at, updated_at FROM session_goals WHERE session_id = ?
`

func (q *Queries) GetSessionGoal(ctx context.Context, sessionID string) (SessionGoal, error) {
	row := q.queryRow(ctx, q.getSessionGoalStmt, getSessionGoal, sessionID)
	var i SessionGoal
	err := row.Scan(
		&i.SessionID,
		&i.ID,
		&i.Objective,
		&i.Status,
		&i.TokenBudget,
		&i.TokensUsed,
		&i.TimeUsedSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveSessionGoal = `-- name: SaveSessionGoal :one
INSERT INTO session_goals (
    session_id, id, objective, status, token_budget, tokens_used,
    time_used_seconds, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(session_id) DO UPDATE SET
    id = excluded.id,
    objective = excluded.objective,
    status = excluded.status,
    token_budget = excluded.token_budget,
    tokens_used = excluded.tokens_used,
    time_used_seconds = excluded.time_used_seconds,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at
RETURNING session_id, id, objective, status, token_budget, tokens_used, time_used_seconds, created_at, updated_at
`

type SaveSessionGoalParams struct {
	SessionID       string        `json:"session_id"`
	ID              string        `json:"id"`
	Objective       string        `json:"objective"`
	Status          string        `json:"status"`
	TokenBudget     sql.NullInt64 `json:"token_budget"`
	TokensUsed      int64         `json:"tokens_used"`
	TimeUsedSeconds float64       `json:"time_used_seconds"`
	CreatedAt       int64         `json:"created_at"`
	UpdatedAt       int64         `json:"updated_at"`
}

func (q *Queries) SaveSessionGoal(ctx context.Context, arg SaveSessionGoalParams) (SessionGoal, error) {
	row := q.queryRow(ctx, q.saveSessionGoalStmt, saveSessionGoal,
		arg.SessionID,
		arg.ID,
		arg.Objective,
		arg.Status,
		arg.TokenBudget,
		arg.TokensUsed,
		arg.TimeUsedSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SessionGoal
	err := row.Scan(
		&i.SessionID,
		&i.ID,
		&i.Objective,
		&i.Status,
		&i.TokenBudget,
		&i.TokensUsed,
		&i.TimeUsedSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
