// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_caches.sql

package db

import (
	"context"
)

const getPromptCache = `-- name: GetPromptCache :one
SELECT id, cache_key, resource, session_id, created_at, expires_at, token_count, creation_cost, invalidated, storage_cost FROM prompt_caches
WHERE cache_key = ? AND expires_at > ? AND invalidated = 0
ORDER BY expires_at DESC
LIMIT 1
`

type GetPromptCacheParams struct {
	CacheKey  string `json:"cache_key"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) GetPromptCache(ctx context.Context, arg GetPromptCacheParams) (PromptCach, error) {
	row := q.queryRow(ctx, q.getPromptCacheStmt, getPromptCache, arg.CacheKey, arg.ExpiresAt)
	var i PromptCach
	err := row.Scan(
		&i.ID,
		&i.CacheKey,
		&i.Resource,
		&i.SessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TokenCount,
		&i.CreationCost,
		&i.Invalidated,
		&i.StorageCost,
	)
	return i, err
}

const insertPromptCache = `-- name: InsertPromptCache :execrows
INSERT INTO prompt_caches (
    id, cache_key, resource, session_id, created_at, expires_at,
    token_count, creation_cost, storage_cost
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type InsertPromptCacheParams struct {
	ID           string  `json:"id"`
	CacheKey     string  `json:"cache_key"`
	Resource     string  `json:"resource"`
	SessionID    string  `json:"session_id"`
	CreatedAt    int64   `json:"created_at"`
	ExpiresAt    int64   `json:"expires_at"`
	TokenCount   int64   `json:"token_count"`
	CreationCost float64 `json:"creation_cost"`
	StorageCost  float64 `json:"storage_cost"`
}

func (q *Queries) InsertPromptCache(ctx context.Context, arg InsertPromptCacheParams) (int64, error) {
	result, err := q.exec(ctx, q.insertPromptCacheStmt, insertPromptCache,
		arg.ID,
		arg.CacheKey,
		arg.Resource,
		arg.SessionID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.TokenCount,
		arg.CreationCost,
		arg.StorageCost,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const invalidatePromptCache = `-- name: InvalidatePromptCache :exec
UPDATE prompt_caches SET invalidated = 1 WHERE id = ?
`

func (q *Queries) InvalidatePromptCache(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.invalidatePromptCacheStmt, invalidatePromptCache, id)
	return err
}
